<?php

use Illuminate\Support\Facades\Schema;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Database\Migrations\Migration;
use Illuminate\Support\Facades\DB;

class CreateIconSeeder extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        DB::statement("truncate fa_icons;");
        DB::statement("           
            INSERT INTO `fa_icons` (`id`, `icon_name`, `icon_status`, `created_at`, `updated_at`) VALUES
(1, 'fa-automobile (alias)', 1, NULL, NULL),
(2, 'fa-bank (alias)', 1, NULL, NULL),
(3, 'fa-behance-square', 1, NULL, NULL),
(4, 'fa-behance', 1, NULL, NULL),
(5, 'fa-cab (alias)', 1, NULL, NULL),
(6, 'fa-bomb', 1, NULL, NULL),
(7, 'fa-building', 1, NULL, NULL),
(8, 'fa-car', 1, NULL, NULL),
(9, 'fa-child', 1, NULL, NULL),
(10, 'fa-circle-o-notch', 1, NULL, NULL),
(11, 'fa-circle-thin', 1, NULL, NULL),
(12, 'fa-codepen', 1, NULL, NULL),
(13, 'fa-cube', 1, NULL, NULL),
(14, 'fa-cubes', 1, NULL, NULL),
(15, 'fa-database', 1, NULL, NULL),
(16, 'fa-delicious', 1, NULL, NULL),
(17, 'fa-deviantart', 1, NULL, NULL),
(18, 'fa-digg', 1, NULL, NULL),
(19, 'fa-drupal', 1, NULL, NULL),
(20, 'fa-empire', 1, NULL, NULL),
(21, 'fa-fax', 1, NULL, NULL),
(22, 'fa-file-archive-o', 1, NULL, NULL),
(23, 'fa-envelope-square', 1, NULL, NULL),
(24, 'fa-file-audio-o', 1, NULL, NULL),
(25, 'fa-file-code-o', 1, NULL, NULL),
(26, 'fa-file-excel-o', 1, NULL, NULL),
(27, 'fa-file-image-o', 1, NULL, NULL),
(28, 'fa-file-movie-o (alias)', 1, NULL, NULL),
(29, 'fa-file-pdf-o', 1, NULL, NULL),
(30, 'fa-file-photo-o (alias)', 1, NULL, NULL),
(31, 'fa-file-picture-o (alias)', 1, NULL, NULL),
(32, 'fa-file-powerpoint-o', 1, NULL, NULL),
(33, 'fa-file-sound-o (alias)', 1, NULL, NULL),
(34, 'fa-file-zip-o (alias)', 1, NULL, NULL),
(35, 'fa-file-word-o', 1, NULL, NULL),
(36, 'fa-file-video-o', 1, NULL, NULL),
(37, 'fa-ge (alias)', 1, NULL, NULL),
(38, 'fa-git', 1, NULL, NULL),
(39, 'fa-google', 1, NULL, NULL),
(40, 'fa-git-square', 1, NULL, NULL),
(41, 'fa-graduation-cap', 1, NULL, NULL),
(42, 'fa-header', 1, NULL, NULL),
(43, 'fa-hacker-news', 1, NULL, NULL),
(44, 'fa-history', 1, NULL, NULL),
(45, 'fa-jsfiddle', 1, NULL, NULL),
(46, 'fa-institution (alias)', 1, NULL, NULL),
(47, 'fa-language', 1, NULL, NULL),
(48, 'fa-joomla', 1, NULL, NULL),
(49, 'fa-life-bouy (alias)', 1, NULL, NULL),
(50, 'fa-life-ring', 1, NULL, NULL),
(51, 'fa-mortar-board (alias)', 1, NULL, NULL),
(52, 'fa-paper-plane-o', 1, NULL, NULL),
(53, 'fa-life-saver (alias)', 1, NULL, NULL),
(54, 'fa-paper-plane', 1, NULL, NULL),
(55, 'fa-openid', 1, NULL, NULL),
(56, 'fa-paragraph', 1, NULL, NULL),
(57, 'fa-paw', 1, NULL, NULL),
(58, 'fa-pied-piper-alt', 1, NULL, NULL),
(59, 'fa-pied-piper', 1, NULL, NULL),
(60, 'fa-qq', 1, NULL, NULL),
(61, 'fa-pied-piper-square (alias)', 1, NULL, NULL),
(62, 'fa-ra (alias)', 1, NULL, NULL),
(63, 'fa-rebel', 1, NULL, NULL),
(64, 'fa-reddit', 1, NULL, NULL),
(65, 'fa-send (alias)', 1, NULL, NULL),
(66, 'fa-recycle', 1, NULL, NULL),
(67, 'fa-reddit-square', 1, NULL, NULL),
(68, 'fa-send-o (alias)', 1, NULL, NULL),
(69, 'fa-share-alt', 1, NULL, NULL),
(70, 'fa-share-alt-square', 1, NULL, NULL),
(71, 'fa-sliders', 1, NULL, NULL),
(72, 'fa-slack', 1, NULL, NULL),
(73, 'fa-soundcloud', 1, NULL, NULL),
(74, 'fa-space-shuttle', 1, NULL, NULL),
(75, 'fa-spotify', 1, NULL, NULL),
(76, 'fa-spoon', 1, NULL, NULL),
(77, 'fa-steam', 1, NULL, NULL),
(78, 'fa-steam-square', 1, NULL, NULL),
(79, 'fa-stumbleupon', 1, NULL, NULL),
(80, 'fa-stumbleupon-circle', 1, NULL, NULL),
(81, 'fa-taxi', 1, NULL, NULL),
(82, 'fa-support (alias)', 1, NULL, NULL),
(83, 'fa-tree', 1, NULL, NULL),
(84, 'fa-tencent-weibo', 1, NULL, NULL),
(85, 'fa-university', 1, NULL, NULL),
(86, 'fa-vine', 1, NULL, NULL),
(87, 'fa-yahoo', 1, NULL, NULL),
(88, 'fa-wordpress', 1, NULL, NULL),
(89, 'fa-wechat (alias)', 1, NULL, NULL),
(90, 'fa-weixin', 1, NULL, NULL),
(91, 'fa-adjust', 1, NULL, NULL),
(92, 'fa-anchor', 1, NULL, NULL),
(93, 'fa-ban', 1, NULL, NULL),
(94, 'fa-asterisk', 1, NULL, NULL),
(95, 'fa-archive', 1, NULL, NULL),
(96, 'fa-bar-chart-o', 1, NULL, NULL),
(97, 'fa-barcode', 1, NULL, NULL),
(98, 'fa-beer', 1, NULL, NULL),
(99, 'fa-bolt', 1, NULL, NULL),
(100, 'fa-book', 1, NULL, NULL),
(101, 'fa-bell', 1, NULL, NULL),
(102, 'fa-bell-o', 1, NULL, NULL),
(103, 'fa-bookmark', 1, NULL, NULL),
(104, 'fa-bookmark-o', 1, NULL, NULL),
(105, 'fa-building', 1, NULL, NULL),
(106, 'fa-briefcase', 1, NULL, NULL),
(107, 'fa-bullhorn', 1, NULL, NULL),
(108, 'fa-bug', 1, NULL, NULL),
(109, 'fa-bullseye', 1, NULL, NULL),
(110, 'fa-calendar', 1, NULL, NULL),
(111, 'fa-camera', 1, NULL, NULL),
(112, 'fa-camera-retro', 1, NULL, NULL),
(113, 'fa-caret-square-o-down', 1, NULL, NULL),
(114, 'fa-calendar-o', 1, NULL, NULL),
(115, 'fa-caret-square-o-left', 1, NULL, NULL),
(116, 'fa-caret-square-o-right', 1, NULL, NULL),
(117, 'fa-check-circle-o', 1, NULL, NULL),
(118, 'fa-certificate', 1, NULL, NULL),
(119, 'fa-caret-square-o-up', 1, NULL, NULL),
(120, 'fa-check', 1, NULL, NULL),
(121, 'fa-check-circle', 1, NULL, NULL),
(122, 'fa-check-square', 1, NULL, NULL),
(123, 'fa-circle', 1, NULL, NULL),
(124, 'fa-check-square-o', 1, NULL, NULL),
(125, 'fa-circle-o', 1, NULL, NULL),
(126, 'fa-clock-o', 1, NULL, NULL),
(127, 'fa-cloud', 1, NULL, NULL),
(128, 'fa-cloud-download', 1, NULL, NULL),
(129, 'fa-cloud-upload', 1, NULL, NULL),
(130, 'fa-coffee', 1, NULL, NULL),
(131, 'fa-code', 1, NULL, NULL),
(132, 'fa-cog', 1, NULL, NULL),
(133, 'fa-code-fork', 1, NULL, NULL),
(134, 'fa-cogs', 1, NULL, NULL),
(135, 'fa-plus-square-o', 1, NULL, NULL),
(136, 'fa-comment-o', 1, NULL, NULL),
(137, 'fa-comment', 1, NULL, NULL),
(138, 'fa-comments', 1, NULL, NULL),
(139, 'fa-comments-o', 1, NULL, NULL),
(140, 'fa-compass', 1, NULL, NULL),
(141, 'fa-credit-card', 1, NULL, NULL),
(142, 'fa-crop', 1, NULL, NULL),
(143, 'fa-crosshairs', 1, NULL, NULL),
(144, 'fa-cutlery', 1, NULL, NULL),
(145, 'fa-dashboard (alias)', 1, NULL, NULL),
(146, 'fa-desktop', 1, NULL, NULL),
(147, 'fa-download', 1, NULL, NULL),
(148, 'fa-ellipsis-horizontal', 1, NULL, NULL),
(149, 'fa-dot-circle-o', 1, NULL, NULL),
(150, 'fa-edit (alias)', 1, NULL, NULL),
(151, 'fa-ellipsis-vertical', 1, NULL, NULL),
(152, 'fa-envelope', 1, NULL, NULL),
(153, 'fa-exclamation', 1, NULL, NULL),
(154, 'fa-eraser', 1, NULL, NULL),
(155, 'fa-envelope-o', 1, NULL, NULL),
(156, 'fa-exclamation-circle', 1, NULL, NULL),
(157, 'fa-exchange', 1, NULL, NULL),
(158, 'fa-exclamation-triangle', 1, NULL, NULL),
(159, 'fa-external-link', 1, NULL, NULL),
(160, 'fa-external-link-square', 1, NULL, NULL),
(161, 'fa-minus-square-o', 1, NULL, NULL),
(162, 'fa-eye-slash', 1, NULL, NULL),
(163, 'fa-eye', 1, NULL, NULL),
(164, 'fa-female', 1, NULL, NULL),
(165, 'fa-film', 1, NULL, NULL),
(166, 'fa-filter', 1, NULL, NULL),
(167, 'fa-fire-extinguisher', 1, NULL, NULL),
(168, 'fa-fire', 1, NULL, NULL),
(169, 'fa-fighter-jet', 1, NULL, NULL),
(170, 'fa-flag', 1, NULL, NULL),
(171, 'fa-flag-checkered', 1, NULL, NULL),
(172, 'fa-flash (alias)', 1, NULL, NULL),
(173, 'fa-flask', 1, NULL, NULL),
(174, 'fa-flag-o', 1, NULL, NULL),
(175, 'fa-folder', 1, NULL, NULL),
(176, 'fa-folder-o', 1, NULL, NULL),
(177, 'fa-folder-open-o', 1, NULL, NULL),
(178, 'fa-frown-o', 1, NULL, NULL),
(179, 'fa-folder-open', 1, NULL, NULL),
(180, 'fa-gavel', 1, NULL, NULL),
(181, 'fa-gamepad', 1, NULL, NULL),
(182, 'fa-gear (alias)', 1, NULL, NULL),
(183, 'fa-gears (alias)', 1, NULL, NULL),
(184, 'fa-glass', 1, NULL, NULL),
(185, 'fa-globe', 1, NULL, NULL),
(186, 'fa-gift', 1, NULL, NULL),
(187, 'fa-group', 1, NULL, NULL),
(188, 'fa-hdd-o', 1, NULL, NULL),
(189, 'fa-heart', 1, NULL, NULL),
(190, 'fa-headphones', 1, NULL, NULL),
(191, 'fa-heart-o', 1, NULL, NULL),
(192, 'fa-home', 1, NULL, NULL),
(193, 'fa-inbox', 1, NULL, NULL),
(194, 'fa-info', 1, NULL, NULL),
(195, 'fa-keyboard-o', 1, NULL, NULL),
(196, 'fa-key', 1, NULL, NULL),
(197, 'fa-laptop', 1, NULL, NULL),
(198, 'fa-info-circle', 1, NULL, NULL),
(199, 'fa-leaf', 1, NULL, NULL),
(200, 'fa-legal (alias)', 1, NULL, NULL),
(201, 'fa-lemon-o', 1, NULL, NULL),
(202, 'fa-level-down', 1, NULL, NULL),
(203, 'fa-level-up', 1, NULL, NULL),
(204, 'fa-lightbulb-o', 1, NULL, NULL),
(205, 'fa-location-arrow', 1, NULL, NULL),
(206, 'fa-lock', 1, NULL, NULL),
(207, 'fa-magic', 1, NULL, NULL),
(208, 'fa-magnet', 1, NULL, NULL),
(209, 'fa-mail-reply (alias)', 1, NULL, NULL),
(210, 'fa-mail-forward (alias)', 1, NULL, NULL),
(211, 'fa-mail-reply-all', 1, NULL, NULL),
(212, 'fa-male', 1, NULL, NULL),
(213, 'fa-microphone', 1, NULL, NULL),
(214, 'fa-map-marker', 1, NULL, NULL),
(215, 'fa-microphone-slash', 1, NULL, NULL),
(216, 'fa-meh-o', 1, NULL, NULL),
(217, 'fa-minus', 1, NULL, NULL),
(218, 'fa-minus-circle', 1, NULL, NULL),
(219, 'fa-mobile', 1, NULL, NULL),
(220, 'fa-minus-square-o', 1, NULL, NULL),
(221, 'fa-money', 1, NULL, NULL),
(222, 'fa-minus-square', 1, NULL, NULL),
(223, 'fa-mobile-phone (alias)', 1, NULL, NULL),
(224, 'fa-moon-o', 1, NULL, NULL),
(225, 'fa-music', 1, NULL, NULL),
(226, 'fa-move', 1, NULL, NULL),
(227, 'fa-pencil', 1, NULL, NULL),
(228, 'fa-pencil-square', 1, NULL, NULL),
(229, 'fa-pencil-square-o', 1, NULL, NULL),
(230, 'fa-phone', 1, NULL, NULL),
(231, 'fa-phone-square', 1, NULL, NULL),
(232, 'fa-picture-o', 1, NULL, NULL),
(233, 'fa-plus', 1, NULL, NULL),
(234, 'fa-plus-circle', 1, NULL, NULL),
(235, 'fa-plane', 1, NULL, NULL),
(236, 'fa-plus-square', 1, NULL, NULL),
(237, 'fa-power-off', 1, NULL, NULL),
(238, 'fa-puzzle-piece', 1, NULL, NULL),
(239, 'fa-print', 1, NULL, NULL),
(240, 'fa-question', 1, NULL, NULL),
(241, 'fa-qrcode', 1, NULL, NULL),
(242, 'fa-question-circle', 1, NULL, NULL),
(243, 'fa-quote-right', 1, NULL, NULL),
(244, 'fa-quote-left', 1, NULL, NULL),
(245, 'fa-random', 1, NULL, NULL),
(246, 'fa-refresh', 1, NULL, NULL),
(247, 'fa-reorder', 1, NULL, NULL),
(248, 'fa-reply', 1, NULL, NULL),
(249, 'fa-resize-horizontal', 1, NULL, NULL),
(250, 'fa-reply-all', 1, NULL, NULL),
(251, 'fa-resize-vertical', 1, NULL, NULL),
(252, 'fa-retweet', 1, NULL, NULL),
(253, 'fa-road', 1, NULL, NULL),
(254, 'fa-rocket', 1, NULL, NULL),
(255, 'fa-rss-square', 1, NULL, NULL),
(256, 'fa-rss', 1, NULL, NULL),
(257, 'fa-search', 1, NULL, NULL),
(258, 'fa-search-minus', 1, NULL, NULL),
(259, 'fa-search-plus', 1, NULL, NULL),
(260, 'fa-share', 1, NULL, NULL),
(261, 'fa-shield', 1, NULL, NULL),
(262, 'fa-share-square', 1, NULL, NULL),
(263, 'fa-shopping-cart', 1, NULL, NULL),
(264, 'fa-sign-in', 1, NULL, NULL),
(265, 'fa-share-square-o', 1, NULL, NULL),
(266, 'fa-sign-out', 1, NULL, NULL),
(267, 'fa-sort', 1, NULL, NULL),
(268, 'fa-smile-o', 1, NULL, NULL),
(269, 'fa-signal', 1, NULL, NULL),
(270, 'fa-sitemap', 1, NULL, NULL),
(271, 'fa-sort-alpha-asc', 1, NULL, NULL),
(272, 'fa-sort-alpha-desc', 1, NULL, NULL),
(273, 'fa-sort-amount-asc', 1, NULL, NULL),
(274, 'fa-sort-desc', 1, NULL, NULL),
(275, 'fa-sort-asc', 1, NULL, NULL),
(276, 'fa-sort-down (alias)', 1, NULL, NULL),
(277, 'fa-sort-amount-desc', 1, NULL, NULL),
(278, 'fa-sort-numeric-asc', 1, NULL, NULL),
(279, 'fa-sort-numeric-desc', 1, NULL, NULL),
(280, 'fa-square', 1, NULL, NULL),
(281, 'fa-square-o', 1, NULL, NULL),
(282, 'fa-sort-up (alias)', 1, NULL, NULL),
(283, 'fa-spinner', 1, NULL, NULL),
(284, 'fa-star', 1, NULL, NULL),
(285, 'fa-star-half', 1, NULL, NULL),
(286, 'fa-star-half-o', 1, NULL, NULL),
(287, 'fa-star-o', 1, NULL, NULL),
(288, 'fa-star-half-empty (alias)', 1, NULL, NULL),
(289, 'fa-star-half-full (alias)', 1, NULL, NULL),
(290, 'fa-subscript', 1, NULL, NULL),
(291, 'fa-sun-o', 1, NULL, NULL),
(292, 'fa-suitcase', 1, NULL, NULL),
(293, 'fa-tablet', 1, NULL, NULL),
(294, 'fa-superscript', 1, NULL, NULL),
(295, 'fa-tachometer', 1, NULL, NULL),
(296, 'fa-tag', 1, NULL, NULL),
(297, 'fa-tags', 1, NULL, NULL),
(298, 'fa-tasks', 1, NULL, NULL),
(299, 'fa-terminal', 1, NULL, NULL),
(300, 'fa-thumbs-down', 1, NULL, NULL),
(301, 'fa-thumb-tack', 1, NULL, NULL),
(302, 'fa-thumbs-o-down', 1, NULL, NULL),
(303, 'fa-thumbs-o-up', 1, NULL, NULL),
(304, 'fa-ticket', 1, NULL, NULL),
(305, 'fa-times-circle', 1, NULL, NULL),
(306, 'fa-times', 1, NULL, NULL),
(307, 'fa-thumbs-up', 1, NULL, NULL),
(308, 'fa-times-circle-o', 1, NULL, NULL),
(309, 'fa-tint', 1, NULL, NULL),
(310, 'fa-toggle-left (alias)', 1, NULL, NULL),
(311, 'fa-toggle-up (alias)', 1, NULL, NULL),
(312, 'fa-toggle-down (alias)', 1, NULL, NULL),
(313, 'fa-toggle-right (alias)', 1, NULL, NULL),
(314, 'fa-trash-o', 1, NULL, NULL),
(315, 'fa-unlock', 1, NULL, NULL),
(316, 'fa-trophy', 1, NULL, NULL),
(317, 'fa-truck', 1, NULL, NULL),
(318, 'fa-umbrella', 1, NULL, NULL),
(319, 'fa-unlock-alt', 1, NULL, NULL),
(320, 'fa-unsorted (alias)', 1, NULL, NULL),
(321, 'fa-user', 1, NULL, NULL),
(322, 'fa-video-camera', 1, NULL, NULL),
(323, 'fa-volume-down', 1, NULL, NULL),
(324, 'fa-upload', 1, NULL, NULL),
(325, 'fa-volume-off', 1, NULL, NULL),
(326, 'fa-volume-up', 1, NULL, NULL),
(327, 'fa-warning (alias)', 1, NULL, NULL),
(328, 'fa-wheelchair', 1, NULL, NULL),
(329, 'fa-check-square', 1, NULL, NULL),
(330, 'fa-wrench', 1, NULL, NULL),
(331, 'fa-check-square-o', 1, NULL, NULL),
(332, 'fa-circle', 1, NULL, NULL),
(333, 'fa-square', 1, NULL, NULL),
(334, 'fa-circle-o', 1, NULL, NULL),
(335, 'fa-dot-circle-o', 1, NULL, NULL),
(336, 'fa-minus-square', 1, NULL, NULL),
(337, 'fa-minus-square-o', 1, NULL, NULL),
(338, 'fa-square-o', 1, NULL, NULL),
(339, 'fa-bitcoin (alias)', 1, NULL, NULL),
(340, 'fa-eur', 1, NULL, NULL),
(341, 'fa-btc', 1, NULL, NULL),
(342, 'fa-dollar (alias)', 1, NULL, NULL),
(343, 'fa-cny (alias)', 1, NULL, NULL),
(344, 'fa-euro (alias)', 1, NULL, NULL),
(345, 'fa-inr', 1, NULL, NULL),
(346, 'fa-gbp', 1, NULL, NULL),
(347, 'fa-money', 1, NULL, NULL),
(348, 'fa-jpy', 1, NULL, NULL),
(349, 'fa-krw', 1, NULL, NULL),
(350, 'fa-rmb (alias)', 1, NULL, NULL),
(351, 'fa-rub', 1, NULL, NULL),
(352, 'fa-rouble (alias)', 1, NULL, NULL),
(353, 'fa-rupee (alias)', 1, NULL, NULL),
(354, 'fa-ruble (alias)', 1, NULL, NULL),
(355, 'fa-try', 1, NULL, NULL),
(356, 'fa-turkish-lira (alias)', 1, NULL, NULL),
(357, 'fa-won (alias)', 1, NULL, NULL),
(358, 'fa-usd', 1, NULL, NULL),
(359, 'fa-yen (alias)', 1, NULL, NULL),
(360, 'fa-align-justify', 1, NULL, NULL),
(361, 'fa-align-center', 1, NULL, NULL),
(362, 'fa-align-left', 1, NULL, NULL),
(363, 'fa-chain-broken', 1, NULL, NULL),
(364, 'fa-bold', 1, NULL, NULL),
(365, 'fa-chain (alias)', 1, NULL, NULL),
(366, 'fa-align-right', 1, NULL, NULL),
(367, 'fa-clipboard', 1, NULL, NULL),
(368, 'fa-columns', 1, NULL, NULL),
(369, 'fa-dedent (alias)', 1, NULL, NULL),
(370, 'fa-copy (alias)', 1, NULL, NULL),
(371, 'fa-cut (alias)', 1, NULL, NULL),
(372, 'fa-file', 1, NULL, NULL),
(373, 'fa-eraser', 1, NULL, NULL),
(374, 'fa-file-o', 1, NULL, NULL),
(375, 'fa-file-text', 1, NULL, NULL),
(376, 'fa-files-o', 1, NULL, NULL),
(377, 'fa-font', 1, NULL, NULL),
(378, 'fa-floppy-o', 1, NULL, NULL),
(379, 'fa-file-text-o', 1, NULL, NULL),
(380, 'fa-indent', 1, NULL, NULL),
(381, 'fa-italic', 1, NULL, NULL),
(382, 'fa-link', 1, NULL, NULL),
(383, 'fa-list-ol', 1, NULL, NULL),
(384, 'fa-list-alt', 1, NULL, NULL),
(385, 'fa-list', 1, NULL, NULL),
(386, 'fa-list-ul', 1, NULL, NULL),
(387, 'fa-outdent', 1, NULL, NULL),
(388, 'fa-paperclip', 1, NULL, NULL),
(389, 'fa-repeat', 1, NULL, NULL),
(390, 'fa-rotate-left (alias)', 1, NULL, NULL),
(391, 'fa-paste (alias)', 1, NULL, NULL),
(392, 'fa-rotate-right (alias)', 1, NULL, NULL),
(393, 'fa-strikethrough', 1, NULL, NULL),
(394, 'fa-text-height', 1, NULL, NULL),
(395, 'fa-scissors', 1, NULL, NULL),
(396, 'fa-table', 1, NULL, NULL),
(397, 'fa-save (alias)', 1, NULL, NULL),
(398, 'fa-text-width', 1, NULL, NULL),
(399, 'fa-th-list', 1, NULL, NULL),
(400, 'fa-th-large', 1, NULL, NULL),
(401, 'fa-underline', 1, NULL, NULL),
(402, 'fa-th', 1, NULL, NULL),
(403, 'fa-undo', 1, NULL, NULL),
(404, 'fa-unlink (alias)', 1, NULL, NULL),
(405, 'fa-angle-double-right', 1, NULL, NULL),
(406, 'fa-angle-double-left', 1, NULL, NULL),
(407, 'fa-angle-double-up', 1, NULL, NULL),
(408, 'fa-angle-down', 1, NULL, NULL),
(409, 'fa-angle-double-down', 1, NULL, NULL),
(410, 'fa-angle-left', 1, NULL, NULL),
(411, 'fa-angle-right', 1, NULL, NULL),
(412, 'fa-angle-up', 1, NULL, NULL),
(413, 'fa-arrow-circle-down', 1, NULL, NULL),
(414, 'fa-arrow-circle-left', 1, NULL, NULL),
(415, 'fa-arrow-circle-o-down', 1, NULL, NULL),
(416, 'fa-arrow-circle-o-left', 1, NULL, NULL),
(417, 'fa-arrow-circle-o-up', 1, NULL, NULL),
(418, 'fa-arrow-circle-right', 1, NULL, NULL),
(419, 'fa-arrow-circle-o-right', 1, NULL, NULL),
(420, 'fa-arrow-circle-up', 1, NULL, NULL),
(421, 'fa-arrow-down', 1, NULL, NULL),
(422, 'fa-arrow-left', 1, NULL, NULL),
(423, 'fa-arrow-right', 1, NULL, NULL),
(424, 'fa-caret-right', 1, NULL, NULL),
(425, 'fa-arrow-up', 1, NULL, NULL),
(426, 'fa-caret-down', 1, NULL, NULL),
(427, 'fa-caret-left', 1, NULL, NULL),
(428, 'fa-caret-square-o-down', 1, NULL, NULL),
(429, 'fa-caret-square-o-left', 1, NULL, NULL),
(430, 'fa-caret-square-o-right', 1, NULL, NULL),
(431, 'fa-caret-square-o-up', 1, NULL, NULL),
(432, 'fa-chevron-circle-down', 1, NULL, NULL),
(433, 'fa-caret-up', 1, NULL, NULL),
(434, 'fa-chevron-circle-left', 1, NULL, NULL),
(435, 'fa-chevron-circle-up', 1, NULL, NULL),
(436, 'fa-chevron-circle-right', 1, NULL, NULL),
(437, 'fa-chevron-left', 1, NULL, NULL),
(438, 'fa-chevron-right', 1, NULL, NULL),
(439, 'fa-chevron-down', 1, NULL, NULL),
(440, 'fa-chevron-up', 1, NULL, NULL),
(441, 'fa-hand-o-down', 1, NULL, NULL),
(442, 'fa-hand-o-up', 1, NULL, NULL),
(443, 'fa-hand-o-right', 1, NULL, NULL),
(444, 'fa-hand-o-left', 1, NULL, NULL),
(445, 'fa-long-arrow-down', 1, NULL, NULL),
(446, 'fa-long-arrow-left', 1, NULL, NULL),
(447, 'fa-long-arrow-right', 1, NULL, NULL),
(448, 'fa-long-arrow-up', 1, NULL, NULL),
(449, 'fa-toggle-down (alias)', 1, NULL, NULL),
(450, 'fa-toggle-left (alias)', 1, NULL, NULL),
(451, 'fa-toggle-right (alias)', 1, NULL, NULL),
(452, 'fa-toggle-up (alias)', 1, NULL, NULL),
(453, 'fa-fast-backward', 1, NULL, NULL),
(454, 'fa-fast-forward', 1, NULL, NULL),
(455, 'fa-eject', 1, NULL, NULL),
(456, 'fa-forward', 1, NULL, NULL),
(457, 'fa-backward', 1, NULL, NULL),
(458, 'fa-arrows-alt', 1, NULL, NULL),
(459, 'fa-play', 1, NULL, NULL),
(460, 'fa-play-circle', 1, NULL, NULL),
(461, 'fa-pause', 1, NULL, NULL),
(462, 'fa-play-circle-o', 1, NULL, NULL),
(463, 'fa-expand', 1, NULL, NULL),
(464, 'fa-compress', 1, NULL, NULL),
(465, 'fa-step-backward', 1, NULL, NULL),
(466, 'fa-step-forward', 1, NULL, NULL),
(467, 'fa-youtube-play', 1, NULL, NULL),
(468, 'fa-adn', 1, NULL, NULL),
(469, 'fa-stop', 1, NULL, NULL),
(470, 'fa-android', 1, NULL, NULL),
(471, 'fa-apple', 1, NULL, NULL),
(472, 'fa-bitbucket-square', 1, NULL, NULL),
(473, 'fa-bitcoin (alias)', 1, NULL, NULL),
(474, 'fa-bitbucket', 1, NULL, NULL),
(475, 'fa-btc', 1, NULL, NULL),
(476, 'fa-css3', 1, NULL, NULL),
(477, 'fa-dropbox', 1, NULL, NULL),
(478, 'fa-dribbble', 1, NULL, NULL),
(479, 'fa-flickr', 1, NULL, NULL),
(480, 'fa-facebook', 1, NULL, NULL),
(481, 'fa-facebook-square', 1, NULL, NULL),
(482, 'fa-foursquare', 1, NULL, NULL),
(483, 'fa-github', 1, NULL, NULL),
(484, 'fa-github-alt', 1, NULL, NULL),
(485, 'fa-gittip', 1, NULL, NULL),
(486, 'fa-github-square', 1, NULL, NULL),
(487, 'fa-google-plus', 1, NULL, NULL),
(488, 'fa-google-plus-square', 1, NULL, NULL),
(489, 'fa-html5', 1, NULL, NULL),
(490, 'fa-instagram', 1, NULL, NULL),
(491, 'fa-linkedin-square', 1, NULL, NULL),
(492, 'fa-linkedin', 1, NULL, NULL),
(493, 'fa-linux', 1, NULL, NULL),
(494, 'fa-maxcdn', 1, NULL, NULL),
(495, 'fa-skype', 1, NULL, NULL),
(496, 'fa-pagelines', 1, NULL, NULL),
(497, 'fa-pinterest-square', 1, NULL, NULL),
(498, 'fa-pinterest', 1, NULL, NULL),
(499, 'fa-renren', 1, NULL, NULL),
(500, 'fa-stack-exchange', 1, NULL, NULL),
(501, 'fa-trello', 1, NULL, NULL),
(502, 'fa-stack-overflow', 1, NULL, NULL),
(503, 'fa-twitter', 1, NULL, NULL),
(504, 'fa-tumblr-square', 1, NULL, NULL),
(505, 'fa-tumblr', 1, NULL, NULL),
(506, 'fa-twitter-square', 1, NULL, NULL),
(507, 'fa-vimeo-square', 1, NULL, NULL),
(508, 'fa-windows', 1, NULL, NULL),
(509, 'fa-vk', 1, NULL, NULL),
(510, 'fa-weibo', 1, NULL, NULL),
(511, 'fa-xing', 1, NULL, NULL),
(512, 'fa-xing-square', 1, NULL, NULL),
(513, 'fa-youtube-play', 1, NULL, NULL),
(514, 'fa-youtube-square', 1, NULL, NULL),
(515, 'fa-ambulance', 1, NULL, NULL),
(516, 'fa-youtube', 1, NULL, NULL),
(517, 'fa-h-square', 1, NULL, NULL),
(518, 'fa-hospital-o', 1, NULL, NULL),
(519, 'fa-medkit', 1, NULL, NULL),
(520, 'fa-stethoscope', 1, NULL, NULL),
(521, 'fa-plus-square', 1, NULL, NULL),
(522, 'fa-user-md', 1, NULL, NULL),
(523, 'fa-wheelchair', 1, NULL, NULL),
(524, 'fa-remove', 1, NULL, NULL);
        ");
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        //
    }
}
